# active spring boot profile
spring:
  profiles:
    active: dev

---
# common - spring configuration
spring:

  # devtools - live reload
  devtools:
    livereload:
      enabled: true

  # mvc
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

---

# dev profile - spring boot configuration

spring:
  config:
    activate:
      on-profile: dev

---

#mybatis
mybatis:
  config-location: classpath:mybatis/configuration.xml
